import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { analyzeStory, createId, type Character, type Location, type Project, type Scene } from './domain';
const KEY='storyteller.project.v1';
const seed:Project={id:'story-1',title:'Untitled story',sourceText:'',characters:[],locations:[],scenes:[],updatedAt:new Date().toISOString()};
const exampleStory={title:'Milo and the Moonlit Forest',sourceText:'Milo, a curious little fox, lived beside the moonlit forest. One evening, Milo met Nora, a girl in a yellow raincoat, at the edge of the woods. Together they followed a trail of silver leaves to a quiet pond. A gentle bear named Bram was waiting there with a lantern. The three friends shared stories until the first birds began to sing.'};
const mockPreview=(label:string,summary:string,index:number)=>`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360" viewBox="0 0 640 360"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${['#e9c09d','#c7d1b8','#b7c6d6'][index]}"/><stop offset="1" stop-color="${['#a9b5a0','#e6c4a4','#d8b7a7'][index]}"/></linearGradient></defs><rect width="640" height="360" rx="18" fill="url(#g)"/><circle cx="510" cy="80" r="42" fill="#fff5d6" opacity=".85"/><path d="M0 285 Q145 215 280 285 T640 270 V360 H0Z" fill="#6c8065" opacity=".7"/><text x="32" y="52" fill="#fffdf7" font-family="sans-serif" font-size="22" font-weight="600">${label}</text><text x="32" y="322" fill="#fffdf7" font-family="sans-serif" font-size="16">${summary.slice(0,58)}</text></svg>`)}`;
const uid=createId;
function load():Project { try { return JSON.parse(localStorage.getItem(KEY)||'null')||seed; } catch { return seed; } }
function App(){
 const [project,setProject]=useState<Project>(load); const [tab,setTab]=useState<'story'|'bible'|'scenes'>('story'); const [saved,setSaved]=useState(true); const [generating,setGenerating]=useState<Record<string,boolean>>({});
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(project));setSaved(true)},[project]);
 const patch=(p:Partial<Project>)=>{setSaved(false);setProject(x=>({...x,...p,updatedAt:new Date().toISOString()}))};
 const runAnalysis=()=>{const hasDrafts=project.characters.length>0||project.locations.length>0||project.scenes.length>0;if(hasDrafts&&!window.confirm('Re-analyze this story and replace the current drafts? Your edited story-bible data will be replaced.'))return;const a=analyzeStory(project.sourceText);patch(a);setTab('bible')};
 const generate=async(id:string)=>{const scene=project.scenes.find(s=>s.id===id);if(!scene||generating[id])return;setGenerating(x=>({...x,[id]:true}));try{const result=window.storyteller?await window.storyteller.generateImages({mode:'composition',subject:'scene',prompt:`${scene.summary}. ${scene.visualDescription}`,variants:3,width:512,height:512}):null;const returned=result?.images?.map(image=>image.filePath||image.dataUrl).filter((value):value is string=>Boolean(value));const variants=returned?.length?returned:['Warm watercolor','Nighttime storybook','Bold paper-cut'].map((label,index)=>mockPreview(label,scene.summary,index));patch({scenes:project.scenes.map(s=>s.id===id?{...s,imageStatus:'generated',imageVariants:variants,selectedImage:variants[0]}:s)})}catch(error){window.alert(error instanceof Error?error.message:'Image generation failed')}finally{setGenerating(x=>({...x,[id]:false}))}};
 const exportProject=()=>{const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${project.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'story'}.story.json`;link.click();URL.revokeObjectURL(url)};
 const importProject=(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const incoming=JSON.parse(String(reader.result)) as Project;if(!incoming.title||!Array.isArray(incoming.scenes))throw new Error('Invalid project');setProject({...incoming,id:incoming.id||uid(),updatedAt:new Date().toISOString()});setSaved(true);setTab('story')}catch{window.alert('That file is not a valid Storyteller project.')}};reader.readAsText(file);event.target.value=''};
 const sceneCount=project.scenes.length;
 return <div className="app"><header><div className="brand"><span className="mark">✦</span><div><strong>Storyteller</strong><small>authoring studio</small></div></div><div className="save">{saved?'Saved locally':'Saving…'}</div><button className="primary" onClick={()=>{patch(seed);setTab('story')}}>New story</button></header>
 <main><aside><div className="stories-heading"><p className="eyebrow">STORIES</p><button className="new-story" onClick={()=>{patch(seed);setTab('story')}}>＋ New story</button></div><button className="story-item selected" onClick={()=>setTab('story')}><span className="story-dot">✦</span><span>{project.title||'Untitled story'}</span></button><div className="story-workspace"><p className="eyebrow">CURRENT STORY</p><button className={tab==='story'?'nav active':'nav'} onClick={()=>setTab('story')}>▣ <span>Story</span></button><button className={tab==='bible'?'nav active':'nav'} onClick={()=>setTab('bible')}>◈ <span>Story bible</span><i>{project.characters.length+project.locations.length||''}</i></button><button className={tab==='scenes'?'nav active':'nav'} onClick={()=>setTab('scenes')}>▤ <span>Scenes</span><i>{sceneCount||''}</i></button></div><div className="side-note"><span>LOCAL PROJECT</span><p>Your work stays on this device. AI steps are drafts until you approve them.</p><div className="project-actions"><button onClick={exportProject}>Export project</button><label>Import project<input type="file" accept="application/json,.json" onChange={importProject}/></label></div></div></aside>
 <section className="content">{tab==='story'&&<Story project={project} patch={patch} analyze={runAnalysis} loadExample={()=>{patch({...exampleStory,characters:[],locations:[],scenes:[]});setTab('story')}}/>} {tab==='bible'&&<Bible project={project} patch={patch} goScenes={()=>setTab('scenes')}/>} {tab==='scenes'&&<Scenes project={project} patch={patch} generate={generate} generating={generating}/>}</section></main></div>
}
function Story({project,patch,analyze,loadExample}:{project:Project;patch:(p:Partial<Project>)=>void;analyze:()=>void;loadExample:()=>void}){return <><div className="hero"><p className="eyebrow">A NEW STORY</p><h1>Give your story a<br/><em>world to live in.</em></h1><p className="lede">Start with the words you already have. Storyteller helps you shape characters, places, and scenes before you make anything permanent.</p></div><div className="card input-card"><label>STORY TITLE</label><input value={project.title} onChange={e=>patch({title:e.target.value})} placeholder="The title of your story"/><label>ORIGINAL STORY TEXT</label><textarea value={project.sourceText} onChange={e=>patch({sourceText:e.target.value})} placeholder="Paste a children's story here…"/><div className="card-footer"><span>{project.sourceText.trim().split(/\s+/).filter(Boolean).length} words</span><div className="story-actions"><button className="ghost" onClick={loadExample}>Load example</button><button className="primary" disabled={!project.sourceText.trim()} onClick={analyze}>Analyze story <span>→</span></button></div></div></div><div className="tip"><span>✦</span><p><strong>How it works</strong><br/>Analysis creates editable drafts. Nothing becomes part of your story bible until you review it.</p></div></>}
function Bible({project,patch,goScenes}:{project:Project;patch:(p:Partial<Project>)=>void;goScenes:()=>void}){return <><div className="page-head"><div><p className="eyebrow">STORY BIBLE</p><h2>Make the world consistent.</h2><p>Review the drafts extracted from <strong>{project.title}</strong>. These become the reusable foundation for your scenes.</p></div><button className="ghost" onClick={()=>patch({characters:[],locations:[],scenes:[]})}>Clear drafts</button></div><div className="grid two"><Entity title="Characters" count={project.characters.length} empty="No characters yet. Analyze a story first.">{project.characters.map((c,i)=><div className="entity" key={c.id}><div className="avatar">{c.name[0]}</div><div className="entity-body"><input value={c.name} onChange={e=>patch({characters:project.characters.map(x=>x.id===c.id?{...x,name:e.target.value}:x)})}/><small>{c.role}</small><textarea value={c.description} onChange={e=>patch({characters:project.characters.map(x=>x.id===c.id?{...x,description:e.target.value}:x)})}/></div><button className="remove" onClick={()=>patch({characters:project.characters.filter(x=>x.id!==c.id)})}>×</button></div>)}</Entity><Entity title="Locations" count={project.locations.length} empty="No locations detected yet.">{project.locations.map(l=><div className="entity" key={l.id}><div className="avatar place">⌂</div><div className="entity-body"><input value={l.name} onChange={e=>patch({locations:project.locations.map(x=>x.id===l.id?{...x,name:e.target.value}:x)})}/><textarea value={l.description} onChange={e=>patch({locations:project.locations.map(x=>x.id===l.id?{...x,description:e.target.value}:x)})}/></div><button className="remove" onClick={()=>patch({locations:project.locations.filter(x=>x.id!==l.id)})}>×</button></div>)}</Entity></div><div className="continue"><span>Next: shape the visual story</span><button className="primary" onClick={goScenes}>Review scenes →</button></div></>}
function Entity({title,count,empty,children}:{title:string;count:number;empty:string;children:React.ReactNode}){return <div className="card entity-card"><div className="section-title"><h3>{title}</h3><span>{count}</span></div>{count?children:<div className="empty">{empty}</div>}</div>}
function Scenes({project,patch,generate,generating}:{project:Project;patch:(p:Partial<Project>)=>void;generate:(id:string)=>void;generating:Record<string,boolean>}){const desktop=Boolean(window.storyteller);return <><div className="page-head"><div><p className="eyebrow">SCENES</p><h2>Turn moments into images.</h2><p>Edit the visual direction before generating. {desktop?'Flux generation runs locally in the desktop app.':'Mock preview mode is active in the browser.'}</p></div><span className="pill">{project.scenes.length} scenes</span></div>{project.scenes.length===0?<div className="card empty large">Analyze a story to create scene drafts.</div>:<div className="scene-list">{project.scenes.map((s,i)=><div className="card scene" key={s.id}><div className="scene-num">{String(i+1).padStart(2,'0')}</div><div className="scene-main"><textarea className="scene-summary" value={s.summary} onChange={e=>patch({scenes:project.scenes.map(x=>x.id===s.id?{...x,summary:e.target.value}:x)})}/><p className="source">{s.sourceText}</p><label>VISUAL DESCRIPTION</label><textarea value={s.visualDescription} onChange={e=>patch({scenes:project.scenes.map(x=>x.id===s.id?{...x,visualDescription:e.target.value}:x)})}/>{s.imageStatus==='generated'&&<div className="preview-grid">{(s.imageVariants||[s.selectedImage||'']).map((variant,index)=><button className={variant===s.selectedImage?'preview selected':'preview'} key={`${s.id}-${index}`} onClick={()=>patch({scenes:project.scenes.map(x=>x.id===s.id?{...x,selectedImage:variant}:x)})}><img src={variant.startsWith('/')?`file://${variant}`:variant} alt={`Variant ${index+1}`} /><span>{index+1}</span></button>)}</div>}<div className="scene-actions">{generating[s.id]?<button className="primary" disabled>Generating…</button>:s.imageStatus==='generated'?<button className="ghost" onClick={()=>generate(s.id)}>Regenerate variants</button>:<button className="primary" onClick={()=>generate(s.id)}>{desktop?'Generate Flux images':'Generate mock previews'}</button>}<button className="ghost" onClick={()=>patch({scenes:project.scenes.filter(x=>x.id!==s.id)})}>Remove</button></div></div></div>)}</div>}</>}
createRoot(document.getElementById('root')!).render(<App/>);
